---

- include: apply.yml                                                 
  when: apply_instance_ha|bool                                               
                                                                                 
- include: undo.yml
  when: undo_instance_ha|bool                                               
