---
- name: Gather undercloud and overcloud facts
  hosts: undercloud overcloud
  gather_facts: yes

- name:  Validate overcloud HA status
  hosts: undercloud
  gather_facts: yes
  roles:
    - validate-ha
